### ISSUE TITLE
关于几个问题请教下

### ISSUE THREAD

**Issue by kailong321200875** [zuozewei/blog-example#3]
![image](https://user-images.githubusercontent.com/32283845/116343143-7922c200-a816-11eb-9db2-f64d4aab234f.png)
这两个步骤应该是在哪里去配置的呢。。在文档里面没有看到配置的步骤

**Comment by zuozewei** [comment]
在 Jenkins job 里面调用这个通知类，具体可以参考：https://zuozewei.blog.csdn.net/article/details/88651741

**Comment by zuozewei** [comment]
> ![image](https://user-images.githubusercontent.com/32283845/116343143-7922c200-a816-11eb-9db2-f64d4aab234f.png)
> 这两个步骤应该是在哪里去配置的呢。。在文档里面没有看到配置的步骤

在 Jenkins job 里面调用这个通知类，具体可以参考：https://zuozewei.blog.csdn.net/article/details/88651741

**Comment by kailong321200875** [comment]
> > ![image](https://user-images.githubusercontent.com/32283845/116343143-7922c200-a816-11eb-9db2-f64d4aab234f.png)
> > 这两个步骤应该是在哪里去配置的呢。。在文档里面没有看到配置的步骤
> 
> 在 Jenkins job 里面调用这个通知类，具体可以参考：https://zuozewei.blog.csdn.net/article/details/88651741

好的，谢谢，我去看看

**Comment by kailong321200875** [comment]
大佬，还是失败了。。。一直没设置成功。你那边方便截图下jenkins的详细配置吗

**Comment by zuozewei** [comment]
> 大佬，还是失败了。。。一直没设置成功。你那边方便截图下jenkins的详细配置吗

哪里失败了？设置就是  Post build task 里面执行下python脚本。这个逻辑蛮清晰的。

**Comment by kailong321200875** [comment]
> > 大佬，还是失败了。。。一直没设置成功。你那边方便截图下jenkins的详细配置吗
> 
> 哪里失败了？设置就是 Post build task 里面执行下python脚本。这个逻辑蛮清晰的。

要运行python脚本，是不是要安装特定的插件才行

**Comment by zuozewei** [comment]
> > > 大佬，还是失败了。。。一直没设置成功。你那边方便截图下jenkins的详细配置吗
> > 
> > 
> > 哪里失败了？设置就是 Post build task 里面执行下python脚本。这个逻辑蛮清晰的。
> 
> 要运行python脚本，是不是要安装特定的插件才行

Jenkins 本地需要安装 Python 环境

**Comment by kailong321200875** [comment]
> Python

jenkins已经安装了环境了，然后这些插件 import configparser 是要重新安装一下吗？也是安装在jenkins本地？

**Comment by kailong321200875** [comment]
> > > > 大佬，还是失败了。。。一直没设置成功。你那边方便截图下jenkins的详细配置吗
> > > 
> > > 
> > > 哪里失败了？设置就是 Post build task 里面执行下python脚本。这个逻辑蛮清晰的。
> > 
> > 
> > 要运行python脚本，是不是要安装特定的插件才行
> 
> Jenkins 本地需要安装 Python 环境

jenkins已经安装了环境了，然后这些插件 import configparser 是要重新安装一下吗？也是安装在jenkins本地？

**Comment by zuozewei** [comment]
![image](https://user-images.githubusercontent.com/17716626/116497900-ffa0d780-a8da-11eb-8f12-bc61de283ee0.png)

**Comment by zuozewei** [comment]
> > > > > 大佬，还是失败了。。。一直没设置成功。你那边方便截图下jenkins的详细配置吗
> > > > 
> > > > 
> > > > 哪里失败了？设置就是 Post build task 里面执行下python脚本。这个逻辑蛮清晰的。
> > > 
> > > 
> > > 要运行python脚本，是不是要安装特定的插件才行
> > 
> > 
> > Jenkins 本地需要安装 Python 环境
> 
> jenkins已经安装了环境了，然后这些插件 import configparser 是要重新安装一下吗？也是安装在jenkins本地？

对，需要 pip 安装 Python 的依赖包
